feat: improve logging (IN-1101)

diff --git a/.circleci/continue_config.yml.tmpl b/.circleci/continue_config.yml.tmpl
--- a/.circleci/continue_config.yml.tmpl
+++ b/.circleci/continue_config.yml.tmpl
@@ -139,6 +139,96 @@ jobs:
           extra_build_args: *node_version_arg
 
 
+  collect-logs:
+    executor: vfcommon/default-executor
+    parameters:
+      cluster:
+        type: string
+        description: Name of the cluster in which the environment exists
+        default: "cm4-vf-dev-br-2-0-p1"
+    steps:
+      - vfcommon/install-vfcli:
+          init-cluster: << parameters.cluster >>
+      - run:
+          name: Install stern
+          command: |
+            curl -sSL https://raw.githubusercontent.com/upciti/wakemeops/main/assets/install_repository | sudo bash
+            sudo apt install stern
+      - run:
+          name: Gather Logs
+          environment:
+            ENV_NAME: {{ .values.e2e_env_name }}
+            LOG_DIR: &log_dir /tmp/pod-logs-{{ .values.e2e_env_name }}
+          command: |
+            # function capture_logs() {
+            #   stern -n "${ENV_NAME:?}" -l "app.kubernetes.io/name=$1" -f > "${LOG_DIR:?}/$1.log"
+            #   # kubectl logs -n "${ENV_NAME:?}" -l "app.kubernetes.io/name=$1" -f > "${LOG_DIR:?}/$1.log"
+            # }
+
+            # mkdir "${LOG_DIR:?}"
+            # capture_logs realtime-http &
+            # kubectl describe nodes -n "${ENV_NAME:?}" > "${LOG_DIR:?}/kube-resources.log" &
+
+            # kubectl events -n "${ENV_NAME:?}" -w \
+            #   | tee /dev/tty \
+            #   | tee "${LOG_DIR:?}/kube-events.log" \
+            #   | grep -q "smoke-test-stop-log-collection" \
+            #   || true
+
+            # echo 'termination event received'
+            # echo 'dumping cluster information'
+
+            # kubectl cluster-info dump -n "${ENV_NAME:?}" --output-directory /tmp/cluster-info
+            job_status=$(circleci-agent job status vfcommon/run-smoke-tests)
+            if [ "$job_status" == "success" ] || [ "$job_status" == "failed" ]; then
+              echo "Job has finished executing"
+            else
+              echo "Job is still running with status $job_status"
+            fi
+      # - store_artifacts:
+      #     name: Store Logs
+      #     path: *log_dir
+      #     destination: logs
+      # - store_artifacts:
+      #     name: Store Cluster Info
+      #     path: /tmp/cluster-info
+      #     destination: cluster-info
+  initial-setup:
+    executor: vfcommon/default-executor
+    steps:
+
+       - run:
+          name: Initial Setup
+          environment:
+          command: |
+            sleep 30
+            echo "Initial Setup done"
+
+  mock-e2e-run:
+    executor: vfcommon/default-executor
+    steps:
+        - run:
+          name: mock-e2e-run
+          environment:
+          command: |
+            sleep 60
+            echo "mock-e2e-run done"
+
+  mock-log-collection:
+    executor: vfcommon/default-executor
+    steps:
+        - run:
+          name: mock-log-collection
+          environment:
+          command: |
+            job_status=$(circleci-agent job status mock-e2e-run)
+            if [ "$job_status" == "success" ] || [ "$job_status" == "failed" ]; then
+              echo "Job has finished executing"
+            else
+              echo "Job is still running with status $job_status"
+            fi
+            echo "mock-log-collection done"
+
 workflows:
   {{- if has $masterProdBranches .values.branch }}
   test-and-release:
@@ -148,112 +238,127 @@ workflows:
   test:
   {{- end }}
     jobs:
-      - install_and_buildx:
-          <<: *slack-fail-post-step
-          context: dev-test
-
-      - test:
-          <<: *slack-fail-post-step
-          context: dev-test
-          requires:
-            - install_and_buildx
-          filters:
-            branches:
-              ignore:
-                - production
-                - /^break-glass.*$/
-
-      - vfcommon/release:
-          <<: *slack-fail-post-step
-          context: dev-test
-          requires:
-            - install_and_buildx
-            - test
-          filters:
-            branches:
-              only: master
-
-      - vfcommon/update_track:
-          context: dev-test
-          image_repo: << pipeline.parameters.container-image-url >>
-          component: << pipeline.parameters.track-component >>
-          remote_docker_version: default
-          extra_build_args: *node_version_arg
-          enable_cache_to: {{ eq .values.branch "master" }}
-          requires:
-            {{- if eq .values.branch "master" }}
-            - test
-            {{- end }}
-            - install_and_buildx
-            - vfcommon/release
-          filters:
-            branches:
-              ignore:
-                - /^break-glass.*$/
-
-      - vfcommon/provision-env:
-          context: dev-test
-          env-name: {{ .values.e2e_env_name }}
-          pool-type: e2e
+      - initial-setup:
           filters: *bors_branches_filters
-      - vfcommon/prepare-env:
-          context: dev-test
-          env-name: {{ .values.e2e_env_name }}
-          branch: {{ .values.branch }}
-          tracked-components: << pipeline.parameters.track-component >>
+      - mock-e2e-run:
+          requires:
+            - initial-setup
           filters: *bors_branches_filters
+      - mock-log-collection:
           requires:
-            - vfcommon/provision-env
-            - vfcommon/update_track
-      - vfcommon/run-smoke-tests:
-          context: dev-test
-          e2e-env-name: {{ .values.e2e_env_name }}
-          requires:
-            # - vfcommon/build-e2e-tests
-            - vfcommon/prepare-env
+            -initial-setup
           filters: *bors_branches_filters
-      - vfcommon/release-env:
-          context: dev-test
-          env-name: {{ .values.e2e_env_name }}
-          requires:
-            - vfcommon/run-smoke-tests
-          filters: *bors_branches_filters
+      # - install_and_buildx:
+      #     <<: *slack-fail-post-step
+      #     context: dev-test
 
-      - vfcommon/sync_branches:
-          check_commit_message: "[bugfix]"
-          ssh_key: << pipeline.parameters.ssh-fingerprint >>
-          checkout: true
-          context: dev-test
-          name: sync-branches-bugfix
-          requires:
-            - install_and_buildx
-            - test
-            - vfcommon/release
-          filters:
-            branches:
-              only: master
+      # - test:
+      #     <<: *slack-fail-post-step
+      #     context: dev-test
+      #     requires:
+      #       - install_and_buildx
+      #     filters:
+      #       branches:
+      #         ignore:
+      #           - production
+      #           - /^break-glass.*$/
 
-      - vfcommon/sync_branches:
-          check_commit_message: "[breakglass]"
-          ssh_key: << pipeline.parameters.ssh-fingerprint >>
-          checkout: true
-          context: dev-test
-          name: sync-branches-break-glass
-          requires:
-            - install_and_buildx
-          filters:
-            branches:
-              only: master
+      # - vfcommon/release:
+      #     <<: *slack-fail-post-step
+      #     context: dev-test
+      #     requires:
+      #       - install_and_buildx
+      #       - test
+      #     filters:
+      #       branches:
+      #         only: master
 
-      - vfcommon/generate_technical_documentation:
-          <<: *slack-fail-post-step
-          context: dev-test
-          requires:
-            - test
-            - vfcommon/release
-          filters:
-            branches:
-              only: master
+      # - vfcommon/update_track:
+      #     context: dev-test
+      #     image_repo: << pipeline.parameters.container-image-url >>
+      #     component: << pipeline.parameters.track-component >>
+      #     remote_docker_version: default
+      #     extra_build_args: *node_version_arg
+      #     enable_cache_to: {{ eq .values.branch "master" }}
+      #     requires:
+      #       {{- if eq .values.branch "master" }}
+      #       - test
+      #       {{- end }}
+      #       - install_and_buildx
+      #       - vfcommon/release
+      #     filters:
+      #       branches:
+      #         ignore:
+      #           - /^break-glass.*$/
+
+      # - vfcommon/provision-env:
+      #     context: dev-test
+      #     env-name: {{ .values.e2e_env_name }}
+      #     pool-type: e2e
+      #     filters: *bors_branches_filters
+      # - vfcommon/prepare-env:
+      #     context: dev-test
+      #     env-name: {{ .values.e2e_env_name }}
+      #     branch: {{ .values.branch }}
+      #     tracked-components: << pipeline.parameters.track-component >>
+      #     filters: *bors_branches_filters
+      #     requires:
+      #       - vfcommon/provision-env
+      #       - vfcommon/update_track
+      # - vfcommon/run-smoke-tests:
+      #     context: dev-test
+      #     e2e-env-name: {{ .values.e2e_env_name }}
+      #     requires:
+      #       # - vfcommon/build-e2e-tests
+      #       - vfcommon/prepare-env
+      #     filters: *bors_branches_filters
+      # - collect-logs:
+      #     context: dev-test
+      #     requires:
+      #       - vfcommon/prepare-env
+      #     filters: *bors_branches_filters
+      # - vfcommon/release-env:
+      #     context: dev-test
+      #     env-name: {{ .values.e2e_env_name }}
+      #     requires:
+      #       - vfcommon/run-smoke-tests
+      #     filters: *bors_branches_filters
+
+      # - vfcommon/sync_branches:
+      #     check_commit_message: "[bugfix]"
+      #     ssh_key: << pipeline.parameters.ssh-fingerprint >>
+      #     checkout: true
+      #     context: dev-test
+      #     name: sync-branches-bugfix
+      #     requires:
+      #       - install_and_buildx
+      #       - test
+      #       - vfcommon/release
+      #     filters:
+      #       branches:
+      #         only: master
+
+      # - vfcommon/sync_branches:
+      #     check_commit_message: "[breakglass]"
+      #     ssh_key: << pipeline.parameters.ssh-fingerprint >>
+      #     checkout: true
+      #     context: dev-test
+      #     name: sync-branches-break-glass
+      #     requires:
+      #       - install_and_buildx
+      #     filters:
+      #       branches:
+      #         only: master
+
+      # - vfcommon/generate_technical_documentation:
+      #     <<: *slack-fail-post-step
+      #     context: dev-test
+      #     requires:
+      #       - test
+      #       - vfcommon/release
+      #     filters:
+      #       branches:
+      #         only: master
 
       # Update Production branch
       - vfcommon/post_image_push_actions:
